_BASE_: "Ego_Exo_SLOWFAST_8x8_R50.yaml"
TRAIN:
  DATASET: epickitchenhandobj
TEST:
  DATASET: epickitchenhandobj
BN:
  USE_PRECISE_STATS: False
MODEL:
  MODEL_NAME: HandObjMultiTaskSlowFastHSlow
HANDOBJ:
  ENABLE: True
  DETS_FOLDER: "data/aux_predictions/epic-100_handobj_predicts"
  HEAD_NUM_CONV: 1
  HEAD_CONV_DIM: 512
  HAND_LOSS_WEIGHT: 3.0
  OBJ_LOSS_WEIGHT: 3.0
  LOSS_MODE: "soft"
